export const Productconst = {
    GETPRODUCT_REQUEST: "GETPRODUCT_REQUEST",
    GETPRODUCT_SUCESS: "GETPRODUCT_SUCESS",
    GETPRODUCT_SUCESS_MEN: "GETPRODUCT_SUCESS_MEN",
    GETPRODUCT_SUCESS_ALL: "GETPRODUCT_SUCESS_ALL",
    GETPRODUCT_SUCESS_WOMEN: "GETPRODUCT_SUCESS_WOMEN",
    GETPRODUCT_FALIUR: "GETPRODUCT_FALIUR",
    ADDCART: "ADDCART",
    REMOVECART: "REMOVECART",
    REMOVEALLCART: "REMOVEALLCART",
    REGISTER_SUCESS: "REGISTER_SUCESS",
    REGISTER_fale: "REGISTER_fale",
    LOGIN_SUCESS: "LOGIN_SUCESS",
    LOGIN_fale: "LOGIN_fale",
    LOGOUT: "LOGOUT",
    GETONEPRODUCT: "GETONEPRODUCT",


}